### PR TITLE
composer.json

### PR DESCRIPTION
**Pull request by fedeisas**
Hi Tom, can you please add composer.json to this library?
Thanks a lot!

### CODE REVIEW

**Comment by mariano** [comment]
@tmaiaroto +1 on this. Thanks @fedeisas ;)

**Comment by tmaiaroto** [comment]
Sorry guys,  was on vacation. Should be all set. On another note, I have like zero time for this library...Is anyone using and/or interested in this? I'd more than happy to accept pull requests and bring in collaborators.

**Comment by mariano** [comment]
@tmaiaroto Yup, we are using it, so whatever I can do to help let me know.

**Comment by tmaiaroto** [comment]
I have to revisit and see where I left off. I had a lot of cool ideas planned for this thing.

**Comment by fedeisas** [comment]
Thanks @tmaiaroto. Count me in to help.

**Comment by mariano** [comment]
@tmaiaroto any chance you can add this package to packagist? I can do it but I wouldn't be able to set up the hook for it to auto update.

**Comment by tmaiaroto** [comment]
Should be all set

**Pull request merged**
